In [31]:
import sympy
import random
import numpy
import scipy.interpolate

In [32]:
secret = 87123872
share = 7
poly_degree = 4

# Algorytm rozdzielający

## Generowanie liczby p

In [33]:

p = sympy.randprime(max(secret, share), 100000000999990000000000000)
p


4428352539433488498058333

In [34]:
t_rand = [random.randint(1,100000000) for _ in range(poly_degree - 1)]
t_rand

[51345866, 15485036, 82303967]

In [35]:
ss = []
for i in range(share):
    _sum = 0
    x = i + 1
    for j in range(1, poly_degree - 1):
        _sum += (t_rand[j - 1] * (x ** (j))) % p
    ss.append((i+1,secret + _sum))
    print(i+1, ss[-1])

1 (1, 153954774)
2 (2, 251755748)
3 (3, 380526794)
4 (4, 540267912)
5 (5, 730979102)
6 (6, 952660364)
7 (7, 1205311698)


# Algorytm łączenia

In [36]:
def prepare_eq(i, s, t):
    lst = []
    for x in range(t):
        lst += [i**x]

    a = [lst]
    b = [s]
    return a, b

def solve(amnt):
    selected = []
    for _ in range(amnt):
        tmp = random.choice(ss)
        while tmp in selected:
            tmp = random.choice(ss)
        selected += [tmp]

    a = []
    b = []
    for sel in selected:
        aa, bb = prepare_eq(sel[0], sel[1], poly_degree)
        a += aa
        b += bb
    a = numpy.array(a)
    b = numpy.array(b)
    print(a, b)

    return round(numpy.linalg.lstsq(a,b)[0][0])

solve(4)

[[  1   6  36 216]
 [  1   1   1   1]
 [  1   3   9  27]
 [  1   5  25 125]] [952660364 153954774 380526794 730979102]


C:\Users\drwho\AppData\Local\Temp/ipykernel_19076/3705690680.py:28: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  return round(numpy.linalg.lstsq(a,b)[0][0])


87123872